name: Publish

on:
  push:
    tags: ["v*"]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup update stable
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo +stable publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
